export const DEFAULT_PARAMS = {
  mapWidth: 20, mapHeight: 10, communeSize: 10,
  nbDistributors: 2, distributorRadius: 2,
  totalHouses: 200, initialHouses: 100,
  newHousesPerMonthMin: 2, newHousesPerMonthMax: 5,
  terrainIssueRate: 0.05,
  ecofloPerDay: 1, eparcoPerDay: 2, maxStock: 100, daysPerWeek: 5,
  tripDuration: 1, installsPerDay: 1,
  priceEparcoInstall: 2000, priceEcofloSale: 1000, priceMaintenanceYear: 100,
  devisToSaleDays: 14, maxDeliveryDays: 20, negativeReviewNeighbors: 5,
  distributorSwitchThreshold: 0.20,
  distributorCompetitorPriceFactor: 0.8,
  maintenanceIntervalYears: 2, maintenanceCostPerVisit: 100,
  // Couts unitaires pour le calcul EBITDA reel (EBITDA = CA - couts)
  costProductionEcoflo: 600, costProductionEparco: 900,
  costPerTrip: 150, fixedCostPerYear: 8000,
  eventLeakMaxDays: 2, eventFactoryClosureDays: 20,
  eventCompetitorDuration: 180, eventCompetitorRadius: 20,
  eventCompetitorCaptureRate: 0.80,
  gameDurationYears: 11,
  daysPerYear: 260, weeksPerYear: 52, daysInMonth: 22,
};